### ISSUE TITLE
When dragging one of the top panels, if dragging starts within the top 10 pixels it does not register as a drag

### ISSUE THREAD

**Issue by dutzi** [nomcopter/react-mosaic#156]
Kind of hard to explain, see video:

https://imgur.com/xsfqZIT

The reason is that once the drag starts, the top "hit area" gets `display: block`, causing React DnD to lose its "grip".

The workaround (not perfect) is adding this to the .css:

```css
.mosaic-drop-target.mosaic > .drop-target-container .drop-target.top {
  bottom: 100%;
  top: -10px;
}
```

This will cause the hit area to be rendered _outside_ of the container, keeping those 10 pixels safe.
